--
-- PostgreSQL database dump
--

\restrict yiMqglwyaGUNQvvRiYjPeL7Hzx6hLDDabwjLvHzjAbHJrgF0RllhJbKmjfLXnRv

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

-- Started on 2026-06-24 00:56:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16524)
-- Name: emergency_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emergency_requests (
    id bigint NOT NULL,
    citizen_name character varying(255),
    contact_number character varying(255),
    location character varying(255),
    request_type character varying(255),
    status character varying(255)
);


ALTER TABLE public.emergency_requests OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16523)
-- Name: emergency_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emergency_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emergency_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16502)
-- Name: requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requests (
    id bigint NOT NULL,
    requester_name character varying(100),
    contact_number character varying(20),
    location character varying(100),
    request_type character varying(50),
    status character varying(30),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.requests OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16501)
-- Name: requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.requests_id_seq OWNER TO postgres;

--
-- TOC entry 4907 (class 0 OID 0)
-- Dependencies: 217
-- Name: requests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.requests_id_seq OWNED BY public.requests.id;


--
-- TOC entry 4747 (class 2604 OID 16505)
-- Name: requests id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests ALTER COLUMN id SET DEFAULT nextval('public.requests_id_seq'::regclass);


--
-- TOC entry 4901 (class 0 OID 16524)
-- Dependencies: 220
-- Data for Name: emergency_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.emergency_requests (id, citizen_name, contact_number, location, request_type, status) FROM stdin;
1	Nimal Perera	0771234567	Colombo	Medical Assistance	PENDING
2	Kasun Silva	0719876543	Kandy	Rescue Team	APPROVED
3	Amara Fernando	0761112233	Galle	Food Supply	PENDING
\.


--
-- TOC entry 4899 (class 0 OID 16502)
-- Dependencies: 218
-- Data for Name: requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.requests (id, requester_name, contact_number, location, request_type, status, created_at) FROM stdin;
\.


--
-- TOC entry 4908 (class 0 OID 0)
-- Dependencies: 219
-- Name: emergency_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.emergency_requests_id_seq', 3, true);


--
-- TOC entry 4909 (class 0 OID 0)
-- Dependencies: 217
-- Name: requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.requests_id_seq', 1, false);


--
-- TOC entry 4752 (class 2606 OID 16530)
-- Name: emergency_requests emergency_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emergency_requests
    ADD CONSTRAINT emergency_requests_pkey PRIMARY KEY (id);


--
-- TOC entry 4750 (class 2606 OID 16508)
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);


-- Completed on 2026-06-24 00:56:46

--
-- PostgreSQL database dump complete
--

\unrestrict yiMqglwyaGUNQvvRiYjPeL7Hzx6hLDDabwjLvHzjAbHJrgF0RllhJbKmjfLXnRv

