spring.application.name=request-service

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/disaster_request_db
spring.datasource.username=postgres
spring.datasource.password=Isuru6106

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Request Service Port
server.port=8086